In [1]:
import numpy as np

In [2]:
l = [1,2,3,4]

In [4]:
x = np.array([1,2,3])

In [6]:
print(x)

[1 2 3]


In [7]:
x

array([1, 2, 3])

In [17]:
y = np.array([1,2,3.5,"Vedu"])

In [18]:
y

array(['1', '2', '3.5', 'Vedu'], dtype='<U32')

In [19]:
type(x)
type(y)

numpy.ndarray

In [20]:
type(x[0])

numpy.int32

In [26]:
type(y[0])

numpy.str_

In [33]:
arr = np.array(l)

In [34]:
arr

array([1, 2, 3, 4])

In [36]:
type(arr)

numpy.ndarray

In [37]:
arr[-1]

4

In [39]:
arr[2:4]

array([3, 4])

In [41]:
l2d = [[1,2,3],[4,5,6],[7,8,9]]

In [42]:
arr2d = np.array(l2d)

In [43]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
arr2d[1][1]

5

In [47]:
arr2d.shape

(3, 3)

In [48]:
len(arr2d)

3

In [57]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [59]:
np.arange(2,6)

array([2, 3, 4, 5])

In [64]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [71]:
x = np.ones(5)

In [72]:
x

array([1., 1., 1., 1., 1.])

In [73]:
type(x[0])

numpy.float64

In [74]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [76]:
x = np.ones((3,5))

In [77]:
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [108]:
y = np.zeros((3,5,3))

In [109]:
y

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [110]:
x = np.zeros((3,5,3))

In [111]:
x

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [112]:
x + 3 

array([[[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]],

       [[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]],

       [[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]]])

In [113]:
x + 37

array([[[37., 37., 37.],
        [37., 37., 37.],
        [37., 37., 37.],
        [37., 37., 37.],
        [37., 37., 37.]],

       [[37., 37., 37.],
        [37., 37., 37.],
        [37., 37., 37.],
        [37., 37., 37.],
        [37., 37., 37.]],

       [[37., 37., 37.],
        [37., 37., 37.],
        [37., 37., 37.],
        [37., 37., 37.],
        [37., 37., 37.]]])

In [114]:
(x+2)*5

array([[[10., 10., 10.],
        [10., 10., 10.],
        [10., 10., 10.],
        [10., 10., 10.],
        [10., 10., 10.]],

       [[10., 10., 10.],
        [10., 10., 10.],
        [10., 10., 10.],
        [10., 10., 10.],
        [10., 10., 10.]],

       [[10., 10., 10.],
        [10., 10., 10.],
        [10., 10., 10.],
        [10., 10., 10.],
        [10., 10., 10.]]])

In [115]:
y + x

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [116]:
x

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [117]:
y

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [120]:
x[1][3][1] = 100

In [121]:
x

array([[[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.]],

       [[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0., 100.,   0.],
        [  0.,   0.,   0.]],

       [[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.]]])

In [124]:
x[1][3][1]

100.0

In [125]:
x.reshape(9,5)

array([[  0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.],
       [100.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.]])

In [126]:
x.reshape(5,5)

ValueError: cannot reshape array of size 45 into shape (5,5)

In [128]:
x.flatten() # Return a copy of the array collapsed into one dimension

array([  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0., 100.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.])

In [136]:
x.any(2)

array([[False, False, False, False, False],
       [False, False, False,  True, False],
       [False, False, False, False, False]])

In [137]:
x

array([[[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.]],

       [[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0., 100.,   0.],
        [  0.,   0.,   0.]],

       [[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.]]])

In [142]:
z = np.arange(30)
z = z.reshape(5,6)

In [143]:
z

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [144]:
z.max()

29

In [145]:
z.mean()

14.5

In [146]:
z.mean(axis=0) # Column wise

array([12., 13., 14., 15., 16., 17.])

In [147]:
z.mean(axis=1) # Row wise

array([ 2.5,  8.5, 14.5, 20.5, 26.5])

In [153]:
np.random.rand(5,3)*10 # random numbers from 0 to 10

array([[6.47966941, 2.5599845 , 8.62163268],
       [5.96269413, 4.1885398 , 6.52364499],
       [7.26217478, 3.39191634, 4.19096631],
       [8.82068426, 5.11648981, 0.48179471],
       [4.13545734, 0.97088837, 2.61645071]])

In [154]:
np.random.rand(5,3)*10+10 # random numbers from 10 to 20

array([[12.66657904, 16.27301418, 15.98436783],
       [14.28916209, 16.76022252, 13.34390283],
       [15.96247993, 10.57095473, 12.32335655],
       [17.01313908, 16.01710068, 19.94761504],
       [17.54379258, 10.03215964, 11.07858913]])